:- include('facts.pl'). 
:- include('modules/random.pl').

:- include('modules/startgame.pl').
:- include('modules/state.pl').
:- use_module('modules/bag.pl').
:- include('modules/map.pl').
:- include('modules/move.pl').
:- include('modules/catchpokemon.pl').
:- include('modules/battle.pl').
:- include('modules/attack.pl').
:- include('modules/defend.pl').
:- include('modules/skill.pl').
:- include('modules/setparty.pl').
:- include('modules/bonuslevelup.pl').
:- include('modules/additem.pl').
:- include('modules/useitem.pl').
:- include('modules/superhyperpotion.pl').
:- include('modules/endgame.pl').